### PR TITLE
Line before sections

### PR DESCRIPTION
**Pull request by MattGyverLee**
Added to Attribute Entities (and thus the publisher stylesheets) and XeLaTeX/FO Publisher transforms. HTML
has this feature by default.

### CODE REVIEW

**Review by AndyBlack — CHANGES_REQUESTED** [review]
These look very good!  A couple of things, though:
1. We should also add a lineheight attribute so the user can control how high/thick the line is.  It could be modeled after the spacebefore attribute.  (My expectation is that some users will like 1pt but others will think that is way too thick and want, say, 0.4pt.  We could default to something like 0.4pt, which I understand is the default for TeX.
2. These two new attributes should be added to section 7.4 "Title Format Information Attributes" of the publisher style sheet documentation.
3. The lines that occur with the XHTML output are there whenever the style calls for a pagebreakbefore or a startonoddpage (see line 1470 of XLingPapPublisherStylesheetXHTMLCSS.xsl).  You could modify this to *also* do it when @linebefore='yes'.  I think that way we won't have the XHTML output differ so much from the FO and XeLaTeX output.

**Comment by MattGyverLee** [comment]
Andy, please check this again.

**Review by AndyBlack — COMMENTED** [review]
Again, these are looking very good.  Some potential improvements:
1) Please add yourself as an author to the publisher style sheet documentation file.
1a) line 14387 should include the new material I recently added but is showing as being deleted (if I'm reading the differences output correctly).
2) On XLingPapFOCommon.xsl, new line 280, is the border-after-width="1pt" attribute needed?
3) On XLingPapPublisherStylesheetFO.xsl, new line 5855, I think you are going to need to make it be "...@linebefore='yes'" like it was before.  If it's just "...@linebefore", then when it is an overt 'no', this condition will be true. 
4) Also, it is better to change the $layoutInfo/sectionTitleLayout/@linebefore-weight to be normalize-space( $layoutInfo/sectionTitleLayout/@linebefore-weight); that way if the user happens to key a space or two in the attribute, the result is empty (which we want).  Speaking from painful experience here ;-)  This should be done for all three outputs (FO, web, and XeLaTeX)
5) I'm not understanding what the final change is in XLingPapPublisherStylesheetXHTMLCSS.xsl.  Is it a missing nl?
6) XLingPapPublisherStylesheetXeLaTeX.xsl, line 5370: I've been using <xsl:text>3</xsl:text> for text like this.

**Comment by MattGyverLee** [comment]
Thanks again, 

1. At one point, I updated my branch from the 7.3 branch to benefit from the new changes. Thus, there may be some oddness in the sequence of additions. Line 14387 has the deletion because (as I understand it) the titleFormatSection reaches WAY beyond front matter. I wasn't exactly sure how to handle your grouping of the attributes, as inheritance creates combinations where the documentation seems inconsistent. I tried to undo my changes of adding "This applies to titles of parts, chapters, sections, and most front and back matter elements.", and maybe I zapped some of yours.
2. Good catch on the border-after-width. Style wasn't needed there either. I wasn't sure in my original testing if I could add and xsl:attribute to an fo:block. 
3. What test do you propose to determine if $layoutInfo/sectionTitleLayout/@linebefore-weight has a valid value? Is the existience of the attribute enough?
4. Done
5. Regarding the last line of XLingPapPublisherStylesheetXHTMLCSS.xsl, I don't know what's going on either, I think it must be the way that Oxygen, Meld, or GitHub Desktop saves files.  The ElementAttributes.dtd file was also automatically being converted to Unix line breaks as soon as I touched it.
6. XLingPapPublisherStylesheetXeLaTeX.xsl, line 5370. Using xsl:text makes way more sense in this case, I had copied that section from elsewhere and [greatly] simplified the calculations.

Should linebefore be implemented in XlingPap.css, and if so, where? I didn't see any reasonable/consistent locations in the css.

**Comment by AndyBlack** [comment]
On 4/25/2017 2:32 PM, erros84 wrote:
    
      Thanks again,
        At one point, I updated my branch from the 7.3 branch to benefit
        from the new changes. Thus, there may be some oddness in the
        sequence of additions. Line 14387 has the deletion because (as I
        understand it) the titleFormatSection reaches WAY beyond front
        matter. 
    
    
    Right.  I had a typo there (most likely I copied the previous
    section and forgot to change "front matter" to "title").  Thanks for
    finding and fixing that.
    
    
      I wasn't exactly sure how to handle your grouping of the
        attributes, as inheritance creates combinations where the
        documentation seems inconsistent. 
    
    
    Please give me some "for instances" where the documentation is
    inconsistent so we can clean this up.
    
    
      I tried to undo my changes of adding "This applies to titles of
        parts, chapters, sections, and most front and back matter
        elements.", and maybe I zapped some of yours.
    
    
    No, I misread it, sorry.  
    
    
    
      Good catch on the border-after-width. Style wasn't needed there
        either. I wasn't sure in my original testing if I could add and
        xsl:attribute to an fo:block.
    
    
    Yes, you can, but you do need to be careful to make sure that what
    immediately follows the element is just attribute(s).  If you goof
    (like I've done on more than one occasion) and add text first and
    then try to insert an attribute, it doesn't work.
    
    
      What test do you propose to determine if
        $layoutInfo/sectionTitleLayout/@linebefore-weight has a valid
        value? Is the existience of the attribute enough?
    
    
    I've been using something like this:
    First, create a variable and use the normalize-space() function on
    the item:
    
    <xsl:variable name="weight"
select="normalize-space($layoutInfo/sectionTitleLayout/@linebefore-weight)"/>
    
    This removes any sequence of just blanks that some users have
    managed to enter and not realized it.
    
    Then do a test like
    string-length($weight) &gt; 0
    
    We then hope they haven't entered junk...  Normally, I've added a
    Schematron test (in XLingPap.sch) to look for valid input.  (If you
    will, the DTD specifies "syntactic" constraints and the Schematron
    specifies "semantic" constraints.)  For example, for font size, we
    have this (line 368ff):
    
        <pattern id="fontsize">
            <title>Check for ill-formed font-size attribute
    values</title>
            <rule context="/lingPaper/languages/language/@font-size |
    /lingPaper/types/type/@font-size |
    /xlingpaper/styledPaper/lingPaper/languages/language/@font-size |
    /xlingpaper/styledPaper/lingPaper/types/type/@font-size |
    /xlingpaper/styledPaper/publisherStyleSheet//@font-size |
    /publisherStyleSheet//@font-size">
                <report test="contains(normalize-space(.),'
    ')">The font-size attribute should not contain a space.  Please
    remove it.</report>
                <report test="string-length(normalize-space(.))
    &gt; 0 and
substring(normalize-space(.),string-length(normalize-space(.))-1,2)!='pt'
    and
    substring(normalize-space(.),string-length(normalize-space(.)),1)!='%'
    and normalize-space(.)!='smaller' and normalize-space(.)!='larger'
    and normalize-space(.)!='large' and normalize-space(.)!='medium' and
    normalize-space(.)!='small' and normalize-space(.)!='x-large' and
    normalize-space(.)!='xx-large' and normalize-space(.)!='x-small' and
    normalize-space(.)!='xx-small'">Warning: this font-size attribute
    does not have a proper unit of measure.   Please use either 'pt' or
    '%'.  The PDF may fail to be produced.</report>
            </rule>
        </pattern>
    
    For linebefore-weight, we could use something like this:
    
        <pattern id="linebefore-weight">
            <title>Check for ill-formed c attribute
    values</title>
            <rule
context="/xlingpaper/styledPaper/publisherStyleSheet/descendant::*/@font-size">
                <report test="contains(normalize-space(.),'
    ')">The linebefore-weight attribute should not contain a space. 
    Please remove it.</report>
                <report test="string-length(normalize-space(.))
    &gt; 0 and
substring(normalize-space(.),string-length(normalize-space(.))-1,2)!='pt'">Warning:
    this linebefore-weight attribute does not end with 'pt'.  Please add
    'pt' after the number.  The PDF may fail to be
    produced.</report>
            </rule>
        </pattern>
    
    (I have not tested this.  You will also need to add a line like <active pattern="linebefore-weight"/> around line 23 at the top.)
    
    
      Regarding the last line of
        XLingPapPublisherStylesheetXHTMLCSS.xsl, I don't know what's
        going on either, I think it must be the way that Oxygen, Meld,
        or GitHub Desktop saves files. The ElementAttributes.dtd file
        was also automatically being converted to Unix line breaks as
        soon as I touched it.
    
    
    OK.
    
      XLingPapPublisherStylesheetXeLaTeX.xsl, line 5370. Using
        xsl:text makes way more sense in this case, I had copied that
        section from elsewhere and [greatly] simplified the
        calculations.
    
    
    OK.
    
    --Andy
    
      —
        You are receiving this because your review was requested.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sillsdev/XLingPap","title":"sillsdev/XLingPap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sillsdev/XLingPap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@erros84 in #3: Thanks again, \r\nAt one point, I updated my branch from the 7.3 branch to benefit from the new changes. Thus, there may be some oddness in the sequence of additions. Line 14387 has the deletion because (as I understand it) the titleFormatSection reaches WAY beyond front matter. I wasn't exactly sure how to handle your grouping of the attributes, as inheritance creates combinations where the documentation seems inconsistent. I tried to undo my changes of adding \"This applies to titles of parts, chapters, sections, and most front and back matter elements.\", and maybe I zapped some of yours.\r\n\r\nGood catch on the border-after-width. Style wasn't needed there either. I wasn't sure in my original testing if I could add and xsl:attribute to an fo:block. \r\n\r\nWhat test do you propose to determine if $layoutInfo/sectionTitleLayout/@linebefore-weight has a valid value? Is the existience of the attribute enough?\r\n\r\nRegarding the last line of XLingPapPublisherStylesheetXHTMLCSS.xsl, I don't know what's going on either, I think it must be the way that Oxygen, Meld, or GitHub Desktop saves files.  The ElementAttributes.dtd file was also automatically being converted to Unix line breaks as soon as I touched it.\r\n\r\nXLingPapPublisherStylesheetXeLaTeX.xsl, line 5370. Using xsl:text makes way more sense in this case, I had copied that section from elsewhere and [greatly] simplified the calculations."}],"action":{"name":"View Pull Request","url":"https://github.com/sillsdev/XLingPap/pull/3#issuecomment-297171443"}}}

**Review by AndyBlack — COMMENTED** [review]
Great job!
Just two minor things now (other than maybe adding the Schematron test, if you want):
1) edit the xlingpap.xxe_add_on file: change the date (in two places) and add a new li item after the "For the Word, Open Office Writer, and RenderX PDF outputs:" for what you've done.  (Whatever you write will show in the About XLingPaper document.)  Which reminds me: after saving the xlingpap.xxe_add_on file, do Tools / Execute Command... / produceAboutXLingPaperPage.  (This only works if you have opened an XLingPaper document during the time you've been using XXE.)
2 ) In the publisher user documentation, change the version number to 3.0.3

**Comment by MattGyverLee** [comment]
Are you still waiting for changes?

**Pull request merged**
